##### Site
url: 'https://adamgian.me'




##### Build
source: src/
destination: dist/
exclude:
    - assets/styles/scss/
    - assets/javascript/main.js
# (src/_layouts/compress.html)
compress_html:
    clippings: all
    comments: all