##### Site
name: Adam Gian
url: https://adamgian.com
email: contact@adamgian.com




##### Build
source: src/
destination: dist/
exclude:
    - assets/styles/scss/
    - assets/javascript/main.js
    - assets/javascript/polyfill.js