##### Site
url: https://www.adamgian.me
email: contact@adamgian.me




##### Build
source: src/
destination: dist/
exclude:
    - assets/styles/scss/
    - assets/javascript/main.js
    - assets/javascript/polyfill.js